### ISSUE TITLE
Q2 Project: BadDNS.org

### ISSUE THREAD

**Issue by aaranmcguire** [aaranmcguire/me#1]
### BadDNS.org

This site will show users what their site resolves to, including what their authoritative nameservers are. 

This site will be hosted on GitHub Pages, but will use a Lua resolver API (Repo is currently private until I have more documentation).

#### Todo:

- [ ] Fix any issues on the resolver API.
- [ ] Create Docker container and tests.
- [ ] Make resolver API Public.
- [ ] Create VueJS application on GitHub Pages that allows users to query the API in a friendly UI.

#### Skills:
Lua, Docker, JavaScript
