### ISSUE TITLE
Q2 Project: BadSSL.org

### ISSUE THREAD

**Issue by aaranmcguire** [aaranmcguire/me#2]
### BadSSL.org

This site will show users what Chrome shows when users visit there site over HTTPS. Basically a personalised report of [badssl.com](https://badssl.com). 

This site will be hosted on GitHub Pages, but will use a API (to be designed and programmed during the project).

#### Todo:

- [ ] Create Scope for BadSSL.org (What will we report and what won't we report).
- [ ] Design API, and select a language (Options: PHP, Lua, Go).
- [ ] Build API and make the repo public.
- [ ] Create API Documentation and Docker Image.
- [ ] Create Tests.
- [ ] Create VueJS application on GitHub Pages that allows users to query the API in a friendly UI.

#### Skills:

SSL, Docker, JavaScript, [PHP, Lua, Go]?
