### ISSUE TITLE
Q2 Idea/Project: Free Whois API

### ISSUE THREAD

**Issue by aaranmcguire** [aaranmcguire/me#4]
### Free Whois API

If time permits, I would like to create a free to use whois API that competes with ones already on the market. This will also be a good opportunity to program in a language I'm not familiar with (Go/Lua).

If I create this site, I will host the API and have a public repo for others to re-host.

#### Todo:

- [ ] Design API, and select a language (Options: PHP, Lua, Go).
- [ ] Build API and make the repo public.
- [ ] Create API Documentation and Docker Image.
- [ ] Create Tests.
- [ ] Create VueJS application on GitHub Pages that allows users to query the API in a friendly UI.

#### Skills:

SSL, Docker, JavaScript, [PHP, Lua, Go]?
