### ISSUE TITLE
Q2 Project: Learn Machine Learning

### ISSUE THREAD

**Issue by aaranmcguire** [aaranmcguire/me#6]
### Learn Machine Learning

Machine learning is a hot topic at the moment, so I would like to try understand where machine learning can be used, and how to make & serve a model.

#### Todo:

- [x] Research machine learning.
- [x] Purchase GPU for creating and testing models.
- [x] Create CLI tool to train a model (using Lua Torch).
- [x] Prove a model works and serve it using a Lua API.

**Comment by aaranmcguire** [comment]
Done, but lots more to do with this project!
